/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package buoi2;

import javax.swing.JOptionPane;

/**
 *
 * @author LOVE
 */
public class DemoRadioButton extends javax.swing.JFrame {

    /**
     * Creates new form DemoRadioButton
     */
    public DemoRadioButton() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblThongMinh = new javax.swing.JLabel();
        rdoThongMinh = new javax.swing.JRadioButton();
        rdoKhongThongMinh = new javax.swing.JRadioButton();
        rdoNgu = new javax.swing.JRadioButton();
        btnResult = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblThongMinh.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblThongMinh.setForeground(new java.awt.Color(51, 51, 255));
        lblThongMinh.setText("Thong minh: ");

        buttonGroup1.add(rdoThongMinh);
        rdoThongMinh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdoThongMinh.setForeground(new java.awt.Color(255, 0, 0));
        rdoThongMinh.setText("Thong minh");
        rdoThongMinh.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                rdoThongMinhAncestorRemoved(evt);
            }
        });
        rdoThongMinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoThongMinhActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoKhongThongMinh);
        rdoKhongThongMinh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdoKhongThongMinh.setForeground(new java.awt.Color(255, 0, 0));
        rdoKhongThongMinh.setText("Khong Thong Minh");
        rdoKhongThongMinh.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                rdoThongMinhAncestorRemoved(evt);
            }
        });
        rdoKhongThongMinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoKhongThongMinhActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoNgu);
        rdoNgu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdoNgu.setForeground(new java.awt.Color(255, 0, 0));
        rdoNgu.setText("Ngu");
        rdoNgu.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                rdoThongMinhAncestorRemoved(evt);
            }
        });
        rdoNgu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoNguActionPerformed(evt);
            }
        });

        btnResult.setBackground(new java.awt.Color(0, 0, 0));
        btnResult.setForeground(new java.awt.Color(255, 255, 255));
        btnResult.setText("Hien Thi Ket Qua");
        btnResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblThongMinh, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdoThongMinh, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdoNgu)
                    .addComponent(rdoKhongThongMinh, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResult))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblThongMinh, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdoThongMinh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdoKhongThongMinh)
                .addGap(18, 18, 18)
                .addComponent(rdoNgu)
                .addGap(27, 27, 27)
                .addComponent(btnResult, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdoThongMinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoThongMinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoThongMinhActionPerformed

    private void rdoKhongThongMinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoKhongThongMinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoKhongThongMinhActionPerformed

    private void rdoNguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoNguActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoNguActionPerformed

    private void rdoThongMinhAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_rdoThongMinhAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoThongMinhAncestorRemoved

    private void btnResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultActionPerformed
        if(rdoThongMinh.isSelected()){
            JOptionPane.showMessageDialog(this, "Ban khon");
        }
        else if(rdoKhongThongMinh.isSelected()){
            JOptionPane.showMessageDialog(this, "Ban khong thong minh");
        }
        else if(rdoNgu.isSelected()){
            JOptionPane.showMessageDialog(this, "Ban Ngu !");
        }
    }//GEN-LAST:event_btnResultActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DemoRadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DemoRadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DemoRadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DemoRadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DemoRadioButton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnResult;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel lblThongMinh;
    private javax.swing.JRadioButton rdoKhongThongMinh;
    private javax.swing.JRadioButton rdoNgu;
    private javax.swing.JRadioButton rdoThongMinh;
    // End of variables declaration//GEN-END:variables
}
