/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package buoi2;

import javax.swing.JOptionPane;

/**
 *
 * @author LOVE
 */
public class DemoDigital extends javax.swing.JFrame {

    /**
     * Creates new form DemoDigital
     */
    public DemoDigital() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnInput = new javax.swing.JButton();
        btnConFom = new javax.swing.JButton();
        btnDigital = new javax.swing.JButton();
        btnDigital2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnInput.setText("Input");
        btnInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputActionPerformed(evt);
            }
        });

        btnConFom.setText("Confom");
        btnConFom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConFomActionPerformed(evt);
            }
        });

        btnDigital.setText("Digital");
        btnDigital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDigitalActionPerformed(evt);
            }
        });

        btnDigital2.setText("Digital2");
        btnDigital2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDigital2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btnInput)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConFom)
                .addGap(66, 66, 66))
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(btnDigital)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(btnDigital2)
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInput)
                    .addComponent(btnConFom))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDigital)
                    .addComponent(btnDigital2))
                .addContainerGap(136, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConFomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConFomActionPerformed
        int choice = JOptionPane.showConfirmDialog(this, "Ban co bi gay khong ?", "TieuDe", JOptionPane.YES_NO_OPTION);
        if(choice == JOptionPane.YES_OPTION)
            JOptionPane.showMessageDialog(this, "Ban bi gay");
        else if(choice == JOptionPane.NO_OPTION)
            JOptionPane.showMessageDialog(this, "Ban khong bi gay");
        else
            JOptionPane.showMessageDialog(this, "Khac");
    }//GEN-LAST:event_btnConFomActionPerformed

    private void btnInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputActionPerformed
        String ten = JOptionPane.showInputDialog(this, "Moi nhap ho ten: ");
        if(!ten.equals(""))
            JOptionPane.showMessageDialog(this, "Xin Chao: "+ ten);
    }//GEN-LAST:event_btnInputActionPerformed

    private void btnDigitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDigitalActionPerformed
        String[] option = {"Python" , "PHP" , "HTML", "JAVA"};
        int choice = JOptionPane.showOptionDialog(this, "Ngon Ngu Yeu Thich: ", "Ngon Ngu", JOptionPane.YES_NO_OPTION, 
                JOptionPane.QUESTION_MESSAGE, null, option, option[0]);
        JOptionPane.showMessageDialog(this, "Ngon ngu yeu thich la: " + option[choice]);
    }//GEN-LAST:event_btnDigitalActionPerformed

    private void btnDigital2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDigital2ActionPerformed
        int Message = JOptionPane.QUESTION_MESSAGE;
        String[] option = {"Java", "C++","PHP","HTML"};
        int ret = JOptionPane.showOptionDialog(this, "Ngon Ngu Ghet Nhat", "Khao Sat", 0,
                Message, null, option, "C++");
        JOptionPane.showMessageDialog(this, "Answer: "+ ret);
    }//GEN-LAST:event_btnDigital2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DemoDigital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DemoDigital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DemoDigital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DemoDigital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DemoDigital().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConFom;
    private javax.swing.JButton btnDigital;
    private javax.swing.JButton btnDigital2;
    private javax.swing.JButton btnInput;
    // End of variables declaration//GEN-END:variables
}
